---
kind: auto.CI
spec:
  compileGHWorkflowsOnly: true
---
kind: common.GHWorkflow
spec:
  jobs:
    - name: default
      buildxOptions:
        enabled: true
        crossBuilder: true
      runners:
        - self-hosted
        - pkgs
      steps:
        - name: build
          nonMakeStep: true
          command: make
        - name: login-to-registry
          registryLoginStep:
            registry: ghcr.io
        - name: push
          nonMakeStep: true
          command: make
          environment:
            PUSH: true
